name: Mondoo Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:

  build:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: Build the binary
        run: go build -o mondoo-webserver ./main.go