name: Release Workflow

on:
  workflow_run:
    workflows: ["Mondoo Pipeline"]
    types:
      - completed

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.CREATE_RELEASE_PAT }}
        goos: linux
        goarch: amd64

  trigger-docker-build:
    runs-on: ubuntu-latest
    needs: [release-linux-amd64]
    steps:
      - name: Trigger Docker Build in Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/msbbn17/phase2/dispatches \
            -d '{"event_type": "trigger-docker-build", "client_payload": {}}'